"use client";

import { useEffect, useMemo, useState } from "react";

type Deck = "eng" | "n2" | "n1" | "kana";
type Mode = "home" | "learn" | "recall" | "exam";
type Word = { id: string; term: string; reading?: string; meaning: string; deck: Deck };
type Saved = { progress: Record<string,{seen:number;mastered:boolean}>; rounds: Record<Deck,number>; history:{date:string;deck:Deck;score:number;total:number}[]; examUnlocked?: Partial<Record<Deck,number>> };

const rows = (deck:Deck, data:[string,string,string?][]) => data.map(([term,meaning,reading],i)=>({id:`${deck}-${i}`,term,meaning,reading,deck}));
const words:Word[] = [
...rows("eng", [["abandon","放弃；抛弃"],["absorb","吸收；使专注"],["abundant","丰富的；大量的"],["accommodate","容纳；适应"],["advocate","提倡；拥护者"],["ambiguous","模棱两可的"],["anticipate","预期；期望"],["arbitrary","任意的；武断的"],["beneficial","有益的"],["coherent","连贯的；一致的"],["compel","强迫；驱使"],["comprehensive","全面的；综合的"],["consecutive","连续的"],["controversial","有争议的"],["crucial","关键的"],["deduce","推断"],["diminish","减少"],["diverse","多样的"],["elaborate","详尽阐述"],["emerge","出现；显现"]]),
...rows("n2", [["曖昧","暧昧；含糊","あいまい"],["予め","预先；事先","あらかじめ"],["改めて","重新；再次","あらためて"],["一層","更加；越发","いっそう"],["概して","一般来说","がいして"],["必ずしも","未必；不一定","かならずしも"],["極めて","极其；非常","きわめて"],["加える","添加；加入","くわえる"],["従って","因此；所以","したがって"],["次第に","逐渐地","しだいに"],["既に","已经","すでに"],["絶えず","不断地","たえず"],["例えば","例如","たとえば"],["単に","仅仅；单纯","たんに"],["常に","经常；总是","つねに"],["特に","特别；尤其","とくに"],["直に","立刻；马上","ただちに"],["殆ど","几乎；大部分","ほとんど"],["予想","预想；预料","よそう"],["割合","比例；比较地","わりあい"]]),
...rows("n1", [["予め","预先；事先","あらかじめ"],["あえて","敢于；特意","あえて"],["あくまで","彻底；始终","あくまで"],["いわゆる","所谓的","いわゆる"],["およそ","大约；大体","およそ"],["極めて","极其；非常","きわめて"],["更に","更加；进一步","さらに"],["実に","实在；确实","じつに"],["遂に","终于；最终","ついに"],["到底","到底；无论如何（不）","とうてい"],["必ずしも","未必；不一定","かならずしも"],["全く","完全；实在","まったく"],["最も","最；最为","もっとも"],["わずか","仅；少量","わずか"],["著しい","显著的","いちじるしい"],["あながち","未必；不见得","あながち"],["あらかじめ","预先；事先","あらかじめ"],["あくる","次；翌","あくる"],["かえって","反而；反倒","かえって"],["ひときわ","格外；尤其","ひときわ"]]),
...rows("kana", [["あ","a","ア"],["い","i","イ"],["う","u","ウ"],["え","e","エ"],["お","o","オ"],["か","ka","カ"],["き","ki","キ"],["く","ku","ク"],["け","ke","ケ"],["こ","ko","コ"],["さ","sa","サ"],["し","shi","シ"],["す","su","ス"],["せ","se","セ"],["そ","so","ソ"],["た","ta","タ"],["ち","chi","チ"],["つ","tsu","ツ"],["て","te","テ"],["と","to","ト"],["な","na","ナ"],["に","ni","ニ"],["ぬ","nu","ヌ"],["ね","ne","ネ"],["の","no","ノ"],["は","ha","ハ"],["ひ","hi","ヒ"],["ふ","fu","フ"],["へ","he","ヘ"],["ほ","ho","ホ"],["ま","ma","マ"],["み","mi","ミ"],["む","mu","ム"],["め","me","メ"],["も","mo","モ"],["や","ya","ヤ"],["ゆ","yu","ユ"],["よ","yo","ヨ"],["ら","ra","ラ"],["り","ri","リ"],["る","ru","ル"],["れ","re","レ"],["ろ","ro","ロ"],["わ","wa","ワ"],["を","wo","ヲ"],["ん","n","ン"]])];
const deckMeta:Record<Deck,{title:string;sub:string;icon:string}>={eng:{title:"考研英语",sub:"核心词汇",icon:"A"},n2:{title:"日语 N2",sub:"进阶词汇",icon:"N2"},n1:{title:"日语 N1",sub:"高阶词汇",icon:"N1"},kana:{title:"五十音",sub:"平假名 · 片假名",icon:"あ"}};
const blank:Saved={progress:{},rounds:{eng:0,n2:0,n1:0,kana:0},history:[],examUnlocked:{eng:0,n2:0,n1:0,kana:0}};
const ipa:Record<string,string>={abandon:"/əˈbændən/",absorb:"/əbˈzɔːrb/",abundant:"/əˈbʌndənt/",accommodate:"/əˈkɑːmədeɪt/",advocate:"/ˈædvəkeɪt/",ambiguous:"/æmˈbɪɡjuəs/",anticipate:"/ænˈtɪsɪpeɪt/",arbitrary:"/ˈɑːrbɪtreri/",beneficial:"/ˌbenɪˈfɪʃl/",coherent:"/koʊˈhɪrənt/",compel:"/kəmˈpel/",comprehensive:"/ˌkɑːmprɪˈhensɪv/",consecutive:"/kənˈsekjətɪv/",controversial:"/ˌkɑːntrəˈvɜːrʃl/",crucial:"/ˈkruːʃl/",deduce:"/dɪˈduːs/",diminish:"/dɪˈmɪnɪʃ/",diverse:"/daɪˈvɜːrs/",elaborate:"/ɪˈlæbərət/",emerge:"/ɪˈmɜːrdʒ/"};
const kanaMap:Record<string,string>={あ:"a",い:"i",う:"u",え:"e",お:"o",か:"ka",き:"ki",く:"ku",け:"ke",こ:"ko",さ:"sa",し:"shi",す:"su",せ:"se",そ:"so",た:"ta",ち:"chi",つ:"tsu",て:"te",と:"to",な:"na",に:"ni",ぬ:"nu",ね:"ne",の:"no",は:"ha",ひ:"hi",ふ:"fu",へ:"he",ほ:"ho",ま:"ma",み:"mi",む:"mu",め:"me",も:"mo",や:"ya",ゆ:"yu",よ:"yo",ら:"ra",り:"ri",る:"ru",れ:"re",ろ:"ro",わ:"wa",を:"o",ん:"n",が:"ga",ぎ:"gi",ぐ:"gu",げ:"ge",ご:"go",ざ:"za",じ:"ji",ず:"zu",ぜ:"ze",ぞ:"zo",だ:"da",で:"de",ど:"do",ば:"ba",び:"bi",ぶ:"bu",べ:"be",ぼ:"bo",ぱ:"pa",ぴ:"pi",ぷ:"pu",ぺ:"pe",ぽ:"po",ゃ:"ya",ゅ:"yu",ょ:"yo",ー:"-"};
const toRomaji=(reading?:string)=>reading?[...reading].map(k=>kanaMap[k]??k).join(""):"";
const richer:Record<string,string>={abandon:"放弃；抛弃；离弃；中止",absorb:"吸收；吸引；理解；使全神贯注",abundant:"丰富的；大量的；充裕的",accommodate:"容纳；适应；为…提供住宿；调节",advocate:"提倡；拥护；主张；拥护者",ambiguous:"模棱两可的；含糊不清的；多义的",anticipate:"预期；期待；预见；先于…行动",arbitrary:"任意的；武断的；专横的",beneficial:"有益的；有利的；有帮助的",coherent:"连贯的；一致的；条理清楚的",compel:"强迫；迫使；使不得不",comprehensive:"全面的；综合的；广泛的",consecutive:"连续的；连贯的；不间断的",controversial:"有争议的；引起争论的",crucial:"关键的；至关重要的；决定性的",deduce:"推断；演绎；推论",diminish:"减少；缩小；贬低；削弱",diverse:"多样的；不同的；多元的",elaborate:"精心制作的；复杂的；详尽阐述",emerge:"出现；显现；浮现；暴露"};
const definition=(w:Word)=>richer[w.term]||w.meaning;
const GROUP_SIZE = 20;

export default function Home(){
 const [user,setUser]=useState(""); const [name,setName]=useState(""); const [saved,setSaved]=useState<Saved>(blank); const [vocabulary,setVocabulary]=useState<Word[]>(words); const [deck,setDeck]=useState<Deck|null>(null); const [mode,setMode]=useState<Mode>("home"); const [group,setGroup]=useState(0); const [i,setI]=useState(0); const [answer,setAnswer]=useState(""); const [show,setShow]=useState(false); const [feedback,setFeedback]=useState<"correct"|"wrong"|null>(null); const [direction,setDirection]=useState<"meaning"|"term">("meaning"); const [examDirection,setExamDirection]=useState<"meaning"|"term">("meaning"); const [exam,setExam]=useState<{items:Word[];answers:string[];done:boolean}|null>(null); const [notice,setNotice]=useState("");
 useEffect(()=>{const u=localStorage.getItem("wordnest-active-user");if(u){setUser(u);load(u)}},[]);
 useEffect(()=>{fetch("vocab.json").then(r=>r.ok?r.json():null).then((data:Word[]|null)=>{if(data)setVocabulary([...data,...words.filter(w=>w.deck==="kana")])}).catch(()=>{})},[]);
 useEffect(()=>{const dock=document.createElement("section");dock.className="translation-dock";dock.setAttribute("aria-label","三语翻译查询");dock.innerHTML='<div class="translation-title"><span>文</span><b>随手翻译</b></div><select aria-label="原文语言"><option value="zh-CN">中文</option><option value="en">English</option><option value="ja">日本語</option></select><i>→</i><select aria-label="目标语言"><option value="zh-CN">中文</option><option value="en" selected>English</option><option value="ja">日本語</option></select><input placeholder="输入要查询的文字"/><button>翻译</button><p class="translation-result" hidden></p>';document.body.appendChild(dock);const [from,to,input,button,result]=[...dock.querySelectorAll("select,input,button,p")] as [HTMLSelectElement,HTMLSelectElement,HTMLInputElement,HTMLButtonElement,HTMLParagraphElement];const run=async()=>{const value=input.value.trim();if(!value)return;button.disabled=true;button.textContent="翻译中…";result.hidden=true;try{if(from.value===to.value)result.textContent=value;else{const r=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(value)}&langpair=${encodeURIComponent(`${from.value}|${to.value}`)}`);const data=await r.json();result.textContent=data?.responseData?.translatedText||"未找到翻译结果。"}result.hidden=false}catch{result.textContent="暂时无法连接翻译服务，请检查网络后重试。";result.hidden=false}finally{button.disabled=false;button.textContent="翻译"}};button.addEventListener("click",run);input.addEventListener("keydown",e=>{if(e.key==="Enter")run()});return()=>dock.remove()},[]);
 const load=(u:string)=>{try{setSaved(JSON.parse(localStorage.getItem(`wordnest-user-${u}`)||"null")||blank)}catch{setSaved(blank)}};
 const chooseUser=()=>{const n=name.trim();if(!n)return;setUser(n);localStorage.setItem("wordnest-active-user",n);load(n)};
 const save=()=>{if(!user)return;localStorage.setItem(`wordnest-user-${user}`,JSON.stringify(saved));setNotice("进度已保存");setTimeout(()=>setNotice(""),1800)};
 const allWords=useMemo(()=>vocabulary.filter(w=>w.deck===deck),[deck,vocabulary]); const totalGroups=Math.max(1,Math.ceil(allWords.length/GROUP_SIZE)); const list=allWords.slice(group*GROUP_SIZE,group*GROUP_SIZE+GROUP_SIZE); const word=list[i%Math.max(list.length,1)]; const mastered=allWords.filter(w=>saved.progress[w.id]?.mastered).length; const examUnlocked=saved.examUnlocked?.[deck||"eng"]??0;
 const openDeck=(d:Deck)=>{setDeck(d);setMode("home");setGroup(0);setI(0);setExam(null);setShow(false);setAnswer("")};
 const changeGroup=(g:number)=>{setGroup(Math.max(0,Math.min(totalGroups-1,g)));setI(0);setExam(null);setMode("home");setShow(false);setAnswer("")};
 const next=()=>{if(!word)return;setSaved(s=>({...s,progress:{...s.progress,[word.id]:{seen:(s.progress[word.id]?.seen||0)+1,mastered:s.progress[word.id]?.mastered||false}}}));setI(x=>x+1);setShow(false);setFeedback(null);setAnswer("")};
 const previous=()=>{setI(x=>x===0?Math.max(0,list.length-1):x-1);setShow(false);setFeedback(null);setAnswer("")};
 const checkRecall=()=>{if(!word)return;const input=answer.trim().toLowerCase();const correct=direction==="term"?input===word.term.toLowerCase():definition(word).split(/[；;、，,]/).some(item=>item.trim().length>1&&(input.includes(item.trim())||item.trim().includes(input)));setFeedback(correct?"correct":"wrong");setShow(true);if(correct)setSaved(s=>({...s,progress:{...s.progress,[word.id]:{seen:(s.progress[word.id]?.seen||0)+1,mastered:true}}}));};
 const revealAnswer=()=>{if(!word)return;setShow(true);setFeedback("wrong");setSaved(s=>({...s,progress:{...s.progress,[word.id]:{seen:(s.progress[word.id]?.seen||0)+1,mastered:false}}}));};
 const startExam=()=>setExam({items:[...list].sort(()=>Math.random()-.5),answers:Array(list.length).fill(""),done:false});
 const speak=(w:Word)=>{window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(w.deck==="eng"?w.term:(w.reading||w.term));u.lang=w.deck==="eng"?"en-US":"ja-JP";u.rate=.82;window.speechSynthesis.speak(u)};
 const grade=()=>{if(!exam||!deck)return;const isCorrect=(w:Word,input:string)=>examDirection==="term"?input.trim().toLowerCase()===w.term.toLowerCase():input.trim().toLowerCase().includes(definition(w).slice(0,2).toLowerCase());const score=exam.items.reduce((n,w,x)=>n+(isCorrect(w,exam.answers[x])?1:0),0);setSaved(s=>{let progress={...s.progress};exam.items.forEach((w,x)=>{if(isCorrect(w,exam.answers[x]))progress[w.id]={seen:(progress[w.id]?.seen||0)+1,mastered:true}});const allPassed=allWords.every(w=>progress[w.id]?.mastered);if(allPassed)allWords.forEach(w=>progress[w.id]={...progress[w.id],mastered:false});return {...s,progress,examUnlocked:{...s.examUnlocked,[deck]:Math.max(s.examUnlocked?.[deck]??0,Math.min(group+1,totalGroups-1))},rounds:{...s.rounds,[deck]:allPassed?s.rounds[deck]+1:s.rounds[deck]},history:[{date:new Date().toLocaleDateString("zh-CN"),deck,score,total:exam.items.length},...s.history]}});setExam({...exam,done:true})};
 if(!user)return <main className="welcome"><div className="logo">W</div><p className="eyebrow">WORDNEST</p><h1>欢迎来到你的词汇小屋。</h1><p>先告诉我怎么称呼你，我会为你建立一份独立的学习进度。</p><input autoFocus value={name} placeholder="输入用户名" onChange={e=>setName(e.target.value)} onKeyDown={e=>e.key==="Enter"&&chooseUser()}/><button className="solid big" onClick={chooseUser}>开始学习 →</button><small>进度仅保存在此浏览器，以用户名区分。</small></main>;
 if(!deck)return <main><header><div className="brand"><span>W</span><div><b>WordNest</b><small>{user} 的词汇小屋</small></div></div><button className="save" onClick={save}>{notice||"保存进度"}</button></header><section className="hero"><div><p className="eyebrow">你好，{user}</p><h1>今天，想去哪里学习？</h1><p>先选择一个词库，再开始你的学习安排。</p></div><div className="leaf">✦</div></section><section className="deck-grid">{(Object.keys(deckMeta) as Deck[]).map(d=>{const m=deckMeta[d], count=vocabulary.filter(w=>w.deck===d).length;return <button className="deck" key={d} onClick={()=>openDeck(d)}><span className={`deck-icon ${d}`}>{m.icon}</span><div><b>{m.title}</b><small>{m.sub}</small></div><em>{count} 词　→</em></button>})}</section><p className="local-note">已加载完整开源词库；每个用户名都有一份独立进度。</p></main>;
 const m=deckMeta[deck];
 return <main><header><button className="back" onClick={()=>setDeck(null)}>← 返回词库</button><div className="brand mini"><span>{m.icon}</span><b>{m.title}</b></div><button className="save" onClick={save}>{notice||"保存进度"}</button></header><section className="deck-head"><div><p className="eyebrow">{m.sub}</p><h1>{m.title}</h1><p>第 {saved.rounds[deck]+1} 周目 · 已通过 {mastered} / {allWords.length} 词</p></div><div className="progress"><i style={{width:`${allWords.length?mastered/allWords.length*100:0}%`}}/></div></section>
 <section className="group-picker"><div><b>选择词组</b><small>所有词组随时可学习、背诵或考试，不受通过进度限制</small></div><nav>{Array.from({length:totalGroups},(_,g)=><button key={g} className={group===g?"chosen":""} onClick={()=>changeGroup(g)}>{g+1}组</button>)}</nav><p>当前第 {group+1} 组 · {list.length} 词</p></section>{mode==="home"&&<section className="mode-grid"><button onClick={()=>setMode("learn")}><strong>记</strong><div><b>记单词</b><small>当前 20 词组 · 词汇与释义</small></div><span>→</span></button><button onClick={()=>setMode("recall")}><strong>背</strong><div><b>背单词</b><small>当前 20 词组 · 双向默写</small></div><span>→</span></button><button onClick={()=>setMode("exam")}><strong>考</strong><div><b>阶段考试</b><small>当前 20 词组 · 可多次挑战</small></div><span>→</span></button></section>}
 {(mode==="learn"||mode==="recall")&&word&&<section className="study"><div className="counter"><button onClick={()=>setMode("home")}>← 学习菜单</button><span>本组 {i%list.length+1} / {list.length}</span></div><article className="card">{mode==="learn"?<><p className="label">{m.title}</p><div className="word-row"><h2>{word.term}</h2><button className="speaker" onClick={()=>speak(word)} aria-label={`朗读 ${word.term}`}>🔊</button></div><p className="pronunciation">{word.deck==="eng"?(ipa[word.term]||word.term):`${word.reading||word.term} · ${toRomaji(word.reading)}`}</p><div className="line"/><p className="meaning">{definition(word)}</p></>:<><button className="switch" onClick={()=>{setDirection(direction==="meaning"?"term":"meaning");setShow(false);setFeedback(null);setAnswer("")}}>切换练习方向</button><div className="word-row"><p className="prompt">{direction==="meaning"?word.term:definition(word)}</p>{direction==="meaning"&&<button className="speaker" onClick={()=>speak(word)} aria-label={`朗读 ${word.term}`}>🔊</button>}</div>{word.reading&&direction==="meaning"&&<p className="pronunciation">{word.reading} · {toRomaji(word.reading)}</p>}<input autoFocus placeholder={direction==="meaning"?"填写任一中文释义":"填写单词"} value={answer} onChange={e=>{setAnswer(e.target.value);setFeedback(null)}} onKeyDown={e=>e.key==="Enter"&&checkRecall()}/>{feedback&&<p className={feedback==="correct"?"feedback good":"feedback bad"}>{feedback==="correct"?"✓ 回答正确，已标记为掌握":"✕ 不正确，再想一想或查看答案"}</p>}{show&&<p className="answer">答案：{direction==="meaning"?definition(word):word.term}</p>}</>}</article><div className="actions">{mode==="recall"&&!show?<><button className="soft" onClick={revealAnswer}>查看答案</button><button className="solid" onClick={checkRecall}>检查答案</button></>:<><button className="soft" onClick={previous}>← 上一词</button><button className="solid" onClick={next}>下一词 →</button></>}</div></section>}
 {mode==="exam"&&<section className="exam"><button className="back" onClick={()=>setMode("home")}>← 学习菜单</button>{!exam?<><p className="eyebrow">第 {group+1} 组 · {list.length} 词 / {list.length} 分</p><h2>阶段考试</h2>{group>examUnlocked?<><p>本组考试将在完成上一组考试后解锁；记单词和背单词不受此限制。</p><button className="soft" onClick={()=>changeGroup(examUnlocked)}>前往已解锁的第 {examUnlocked+1} 组</button></>:<><p>只要提交本组考试，就会解锁下一组考试。答对的单词将标记为掌握；答错的单词可在以后反复挑战补齐。</p><button className="switch" onClick={()=>setExamDirection(examDirection==="meaning"?"term":"meaning")}>{examDirection==="meaning"?"切换为：看中文填英文 / 日文":"切换为：看单词填中文释义"}</button><br/><button className="solid big" onClick={startExam}>开始本组考试</button></>}</>:exam.done?<div className="result"><p>本次答对的单词已记录，并已解锁下一组考试。</p><strong>{saved.history[0]?.score}<small> / {exam.items.length}</small></strong><button className="solid" onClick={()=>{setExam(null);setMode("home")}}>完成</button></div>:<><p className="eyebrow">{examDirection==="meaning"?"看单词，填中文释义":"看中文释义，填英文 / 日文"}</p><div className="questions">{exam.items.map((w,x)=><label key={w.id}><b>{x+1}</b><span>{examDirection==="meaning"?`${w.term}${w.reading?` · ${w.reading}`:""}`:definition(w)}</span><input placeholder={examDirection==="meaning"?"填写中文释义":"填写英文 / 日文单词"} value={exam.answers[x]} onChange={e=>{const a=[...exam.answers];a[x]=e.target.value;setExam({...exam,answers:a})}}/></label>)}</div><button className="solid big" onClick={grade}>交卷并记录</button></>}</section>}
 </main>;
}
